# Generated by Django 2.1.2 on 2018-10-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveHttpRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=6)),
                ('request_path', models.CharField(max_length=150)),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['request_datetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['date_publish']},
        ),
        migrations.AlterField(
            model_name='book',
            name='authors_info',
            field=models.CharField(max_length=150),
        ),
    ]
