# Generated by Django 3.0.1 on 2020-08-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20181019_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savehttprequests',
            options={'ordering': ['-request_datetime']},
        ),
    ]
